language: node_js
node_js:
  - "6"
script: npm run testCoverage
before_script:
  - echo 'Canada/Pacific' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
after_success: 'npm run coveralls'
