pipeline {
    agent {
        dockerfile {
            filename './jenkins/Dockerfile' 
            args '-p 3000:3000'
            args '--tmpfs /.config'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') { 
            steps {
                sh 'npm install'
                sh 'npm build'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
        stage('Deliver') { 
            steps {
                // input message: 'Make suer everything is ok (Click "Proceed" to deploy to the production server)' 
                sshagent(credentials : ['abe0d167-e79b-49f2-b141-832e0f302786']) {
                    sh 'ssh -o StrictHostKeyChecking=no ubuntu@orderstaker.kevin-project.com sudo rm /var/www/html/*.*'	
                    sh 'scp -r -o StrictHostKeyChecking=no /var/jenkins_home/workspace/OrdersTakerFrontEnd/dist/*.* ubuntu@orderstaker.kevin-project.com:/var/www/html'	
                }
            }
        }
    }
}